### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [w4mxl/V2LF#12]
请问是否可以将应用打包发布到 [F-Droid](https://f-droid.org)？

**Comment by w4mxl** [comment]
你好：

抱歉，V2LF 实际已经停更挺久了，在更新新的版本前不想将其在发布到其它平台了。

linsui ***@***.***> 于2022年1月31日周一 18:22写道：

**Comment by linsui** [comment]
好的，谢谢！
