### ISSUE TITLE
Not working, server is down

### ISSUE THREAD

**Issue by newdev4life** [w4mxl/V2LF#2]
> flutter: DioError [DioErrorType.DEFAULT]: SocketException: Failed host lookup: 'jiasule.v2ex.com' (OS Error: nodename nor servname provided, or not known, errno = 8)
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: SocketException: Failed host lookup: 'jiasule.v2ex.com' (OS Error: nodename nor servname provided, or not known, errno = 8)

Load nothing at all.

**Comment by w4mxl** [comment]
@JimJayLee Please check to see if it is the latest code at your side. "jiasule.v2ex.com" is no longer used for V2LF in a previous update.

**Comment by newdev4life** [comment]
Thanks. Forked code not worked.
