### ISSUE TITLE
运行失败 求解

### ISSUE THREAD

**Issue by GitHubAsural** [w4mxl/V2LF#3]
* Error running Gradle:
ProcessException: Process "D:\V2LF-master\android\gradlew.bat" exited abnormally:

  Command: D:\V2LF-master\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.

**Comment by iFlicker** [comment]
同上 怀疑gradle版本问题，暂未解决

**Comment by w4mxl** [comment]
@GitHubAsural 我这边在 Android 上试了正常的。看你错误信息确实应该是 @iFlicker 说到的跟 gradle 版本有关。

https://github.com/w4mxl/V2LF/blob/c3908e78cf5973b6cae88d468ad02c538981a60f/android/gradle/wrapper/gradle-wrapper.properties#L6

你们可以尝试把代码上面位置中的 gradle 版本改为 gradle-5.6.2-all.zip，再试试看哦。

**Comment by iFlicker** [comment]
换成5.6.2还是这样，对比看了下其他项目 发现问题就是在执行
/Volumes/Data/Flutter/flutter-projects/V2LF/android/gradlew app:properties
这条，手动试了下 如果在V2LF下执行就报错，如果在V2LF/android下执行就没问题。
看flutter run -v 的执行目录是没有问题的
 executing: [/Volumes/Data/Flutter/flutter-projects/V2LF/android/]
/Volumes/Data/Flutter/flutter-projects/V2LF/android/gradlew app:properties

其他项目也是，但是其他项目 flutter run -v的时候不会报错，会不会跟flutter版本有关？还是说有什么设置？@w4mxl

**Comment by w4mxl** [comment]
@iFlicker 

请你再试试把 android/build.gradle 中的：
`ext.kotlin_version = '1.3.31'`
改成：
`ext.kotlin_version = '1.3.50'`

**Comment by iFlicker** [comment]
@w4mxl  还是一样的错误，我已经查到flutter_tools 里了。。

在官方仓库也提了issues
https://github.com/flutter/flutter/issues/46845

**Comment by w4mxl** [comment]
@GitHubAsural 你把 flutter 升级到最新的 stable 1.12.13+hotfix.5 版本，然后拉取项目最新的代码，应该就没有这个问题了哦。
