### ISSUE TITLE
模拟器运行错误

### ISSUE THREAD

**Issue by qixm-burnish** [w4mxl/V2LF#6]
在macos的模拟器(iphone/android)上运行，多滑动几个tab时，就会出现一下错误：
A ScrollController was used after being desposed.
(http://public.onlyoup.top/Screenshot_1589787753.png) 
http://public.onlyoup.top/Screenshot_1589787753.png

**Comment by w4mxl** [comment]
@qixm-burnish 修复了下，你 pull 最新的代码试试呢（可能还有更好的解决方案）
