### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by KunlunLu** [w4mxl/V2LF#8]
<img width="1014" alt="截屏2020-07-18 下午3 07 17" src="https://user-images.githubusercontent.com/22537658/87847180-84040a00-c908-11ea-9bc1-823805558a1c.png">

**Comment by w4mxl** [comment]
我在 Flutter stable, v1.17.5 看了下， zefyr 0.10.0 没有这个问题。
你如果是在其它 Flutter SDK 分支上，可以试试这个解决方案：https://github.com/memspace/zefyr/issues/349#issuecomment-658102964
