### ISSUE TITLE
TF版本过期

### ISSUE THREAD

**Issue by L1cardo** [w4mxl/V2LF#9]
想问一下，TF版本过期了，是不再打算提供TF版本了吗？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by w4mxl** [comment]
嗯，是的。除非有较大的功能新增或改动，否则就不会更新 TF 版本了。

Licardo <notifications@github.com> 于2020年12月2日周三 上午10:37写道：
